import java.sql.Date;
import java.sql.DriverManager;
//import static java.sql.JDBCType.DATE;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Porag
 */
public class EmployeeDetailsPage extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDetailsPage
     */
    public EmployeeDetailsPage() {
        initComponents();
        getEmpTableData();
    }

    private void getEmpTableData(){
        java.sql.Connection conn=null;
        java.sql.Statement st=null;
        
        try{
            conn = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/ssdb","root","");
            st = conn.createStatement();
            String sql="SELECT * FROM EmpTable ";
            ResultSet rs = st.executeQuery(sql);
            DefaultTableModel model = new DefaultTableModel(new String[]{"EmpName", "EmpID", "EmpAddress", "EmpPhnNo" ,"EmpNID","EmpBG","EmpDOB","EmpUserName","EmpPassword"}, 0);
            while(rs.next())
            {
                String  col1 = rs.getString("EmpName");
                String  col2 = rs.getString("EmpID");
                String  col3 = rs.getString("EmpAddress");                
                String  col4 = rs.getString("EmpPhnNo");
                String  col5 = rs.getString("EmpNID");
                String  col6 = rs.getString("EmpBG");
                String  col7 = rs.getString("EmpDOB");
                String  col8 = rs.getString("EmpUserName");
                String  col9 = rs.getString("EmpPassword");
                  
                model.addRow(new Object[]{col1, col2, col3, col4,col5, col6, col7, col8,col9});
            }
            jTableEmpInfo.setModel(model);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    
    public void theQuery(String query){
        java.sql.Connection conn=null;
        java.sql.Statement st=null;
        try{
            conn = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/ssdb","root","");
            st = conn.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Congratulations!! The operation done successfully.");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    private void refreshMethod(){
        jTextFieldName.setEditable(true);
        jTextFieldEmpID.setEditable(true); 
        jTextFieldUserName.setEditable(true);
        
        jTextFielEmpdAdd.setText("");
        jTextFieldEmpNID.setText("");
        jTextFieldDOB.setText("");
        jTextFieldPhn.setText("");        
        jTextFieldBG.setText("");
        jTextFieldDOB.setText("");
        jTextFieldPass.setText("");
     
        getEmpTableData(); 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelEmpName = new javax.swing.JLabel();
        jLabelEmpAddress = new javax.swing.JLabel();
        jLabelEmpID = new javax.swing.JLabel();
        jLabelEmpPhoneNo = new javax.swing.JLabel();
        jLabelEmpDepartment = new javax.swing.JLabel();
        jLabelEmpNationalID = new javax.swing.JLabel();
        jLabelEmpBloodGroup = new javax.swing.JLabel();
        jLabelDateOfBirth = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        jButtonEmpBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmpInfo = new javax.swing.JTable();
        jTextFieldName = new javax.swing.JTextField();
        jTextFielEmpdAdd = new javax.swing.JTextField();
        jTextFieldEmpID = new javax.swing.JTextField();
        jTextFieldPhn = new javax.swing.JTextField();
        jTextFieldBG = new javax.swing.JTextField();
        jTextFieldEmpNID = new javax.swing.JTextField();
        jTextFieldDOB = new javax.swing.JTextField();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabelDateOfBirth1 = new javax.swing.JLabel();
        jTextFieldPass = new javax.swing.JTextField();
        jButtonRefresh = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelEmpName.setText("Name");

        jLabelEmpAddress.setText("Address");

        jLabelEmpID.setText("Employee ID");

        jLabelEmpPhoneNo.setText("Phone No");

        jLabelEmpDepartment.setText("National ID");

        jLabelEmpNationalID.setText("Blood Group");

        jLabelEmpBloodGroup.setText("Date OF Birth");

        jLabelDateOfBirth.setText("UserName");

        jButtonEdit.setText("Edit Information");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonEmpBack.setText("Back");
        jButtonEmpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpBackActionPerformed(evt);
            }
        });

        jTableEmpInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableEmpInfo);

        jTextFielEmpdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielEmpdAddActionPerformed(evt);
            }
        });

        jTextFieldEmpNID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpNIDActionPerformed(evt);
            }
        });

        jLabelDateOfBirth1.setText("Password");

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelEmpBloodGroup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelEmpNationalID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelEmpDepartment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelEmpAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelEmpID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelEmpName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addComponent(jLabelDateOfBirth1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                            .addComponent(jLabelEmpPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFielEmpdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmpNID, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPhn, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBG, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEmpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielEmpdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmpPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPhn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmpDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmpNID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEmpNationalID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmpBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDateOfBirth1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButtonEmpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEmpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpBackActionPerformed
        this.setVisible(false);
        new EmployeeHomePage().setVisible(true);
    }//GEN-LAST:event_jButtonEmpBackActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        if(jTableEmpInfo.getSelectedRow()==-1){
            if(jTableEmpInfo.getSelectedRow()==0){
                JOptionPane.showMessageDialog(null, "Table is empty!!");
            }
            else{
                JOptionPane.showMessageDialog(null, "You need to select an user");
            }
        }   
    
    else{
        jTextFieldUserName.setEditable(false);
        jTextFieldEmpID.setEditable(false);
        jTextFieldUserName.setEditable(false);
        
        int selectedRowIndex = jTableEmpInfo.getSelectedRow();        
        if(jTextFielEmpdAdd.getText().equals("") && jTextFieldEmpNID.getText().equals("") && jTextFieldPhn.getText().equals("")&& jTextFieldBG.getText().equals("")&& jTextFieldDOB.getText().equals("")&& jTextFieldPass.getText().equals("")){
            jTextFielEmpdAdd.setText(jTableEmpInfo.getModel().getValueAt(selectedRowIndex, 2).toString());
            jTextFieldPhn.setText(jTableEmpInfo.getModel().getValueAt(selectedRowIndex, 3).toString());
            jTextFieldEmpNID.setText(jTableEmpInfo.getModel().getValueAt(selectedRowIndex, 4).toString());
            jTextFieldBG.setText(jTableEmpInfo.getModel().getValueAt(selectedRowIndex, 5).toString());
            jTextFieldDOB.setText(jTableEmpInfo.getModel().getValueAt(selectedRowIndex, 6).toString());
            jTextFieldPass.setText(jTableEmpInfo.getModel().getValueAt(selectedRowIndex, 8).toString());
        }
            
        else if(!jTextFielEmpdAdd.getText().equals(jTableEmpInfo.getModel().getValueAt(selectedRowIndex, 2).toString())||
                !jTextFieldPhn.getText().equals(jTableEmpInfo.getModel().getValueAt(selectedRowIndex, 3).toString())||
                !jTextFieldEmpNID.getText().equals(jTableEmpInfo.getModel().getValueAt(selectedRowIndex, 4).toString())||
                !jTextFieldBG.getText().equals(jTableEmpInfo.getModel().getValueAt(selectedRowIndex, 5).toString())||
                !jTextFieldDOB.getText().equals(jTableEmpInfo.getModel().getValueAt(selectedRowIndex, 6).toString())||
                !jTextFieldPass.getText().equals(jTableEmpInfo.getModel().getValueAt(selectedRowIndex, 8).toString())){            
                 theQuery("update emptable set EmpAddress='"+jTextFielEmpdAdd.getText()+"'EmpPhnNo='"+jTextFieldPhn.getText()+"'EmpNID='"+jTextFieldEmpNID.getText()+"'EmpBG='"+jTextFieldBG.getText()+"'EmpDOB='"+jTextFieldDOB.getText()+"'EmpPassword = "+jTextFieldPass.getText()+"' where EmpID="+jTextFieldEmpID.getText());
        
        }
        else{
            JOptionPane.showMessageDialog(null,"You dont't update the value!!");
        }
    }    
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jTextFielEmpdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielEmpdAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielEmpdAddActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        refreshMethod();
        getEmpTableData(); 
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jTextFieldEmpNIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpNIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpNIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetailsPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonEmpBack;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabelDateOfBirth;
    private javax.swing.JLabel jLabelDateOfBirth1;
    private javax.swing.JLabel jLabelEmpAddress;
    private javax.swing.JLabel jLabelEmpBloodGroup;
    private javax.swing.JLabel jLabelEmpDepartment;
    private javax.swing.JLabel jLabelEmpID;
    private javax.swing.JLabel jLabelEmpName;
    private javax.swing.JLabel jLabelEmpNationalID;
    private javax.swing.JLabel jLabelEmpPhoneNo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableEmpInfo;
    private javax.swing.JTextField jTextFielEmpdAdd;
    private javax.swing.JTextField jTextFieldBG;
    private javax.swing.JTextField jTextFieldDOB;
    private javax.swing.JTextField jTextFieldEmpID;
    private javax.swing.JTextField jTextFieldEmpNID;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPass;
    private javax.swing.JTextField jTextFieldPhn;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
