import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import com.mysql.jdbc.Connection;
//import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
//import javax.swing.JOptionPane;

/**
 *
 * @author Porag
 */
public class LogInHomePage extends javax.swing.JFrame {
    public static Connection conn =null;
     java.sql.Statement st=null;
    //private Connection connection;
    //private Statement statement;
    //PreparedStatement pst = null;

  
    public LogInHomePage() {
        initComponents();
        groupButton();
        //visible();
        
    }
    public void groupButton(){
        ButtonGroup bg1=new ButtonGroup();
        bg1.add(jRadioButtonEmployee);
        bg1.add(jRadioButtonCustomer);
        
    }
    
    /*private void visible(){
        jRadioButtonEmployee.setSelected(true);
        jRadioButtonCustomer.setSelected(false);
    }*/
    //dispose, exit(), setvisible
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabelLogInAs = new javax.swing.JLabel();
        jRadioButtonEmployee = new javax.swing.JRadioButton();
        jRadioButtonCustomer = new javax.swing.JRadioButton();
        jLabelUserName = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JPasswordField();
        jTextFieldUserName = new javax.swing.JTextField();
        jButtonLogIn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonRegestration = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelLogInAs.setText("  Log In As :");

        buttonGroup.add(jRadioButtonEmployee);
        jRadioButtonEmployee.setText("Employee");
        jRadioButtonEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmployeeActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButtonCustomer);
        jRadioButtonCustomer.setText("Customer");
        jRadioButtonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCustomerActionPerformed(evt);
            }
        });

        jLabelUserName.setText(" User Name  ");

        jLabelPassword.setText(" Password   ");

        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });

        jButtonLogIn.setText("LogIn");
        jButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogInActionPerformed(evt);
            }
        });

        jButtonRegestration.setText("Registration");
        jButtonRegestration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegestrationActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("   Click on registration button to be registered. ");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegestration, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelLogInAs, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jRadioButtonEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jTextFieldPassword))
                        .addGap(30, 30, 30)
                        .addComponent(jButtonLogIn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelLogInAs, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCustomer)
                    .addComponent(jRadioButtonEmployee))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButtonLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRegestration, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogInActionPerformed
        
        if( jRadioButtonEmployee.isSelected()== true) {
            try {
                if(!jTextFieldUserName.getText().equals("")&& !jTextFieldPassword.getText().equals("")){
                
                java.sql.Connection conn=null;
                java.sql.Statement st=null;
                conn = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/ssdb","root","");
                st = conn.createStatement();
                String sql = "SELECT * FROM emptable WHERE EmpUserName='"+jTextFieldUserName.getText()+"' AND EmpPassword='"+ jTextFieldPassword.getText()+"'";
                ResultSet rs = st.executeQuery(sql);
                   
                if(!rs.next()){
                JOptionPane.showMessageDialog(null, "Sorry Wrong Password.");
                    }
                
                else{
                    
                JOptionPane.showMessageDialog(null, "Successfull");
                new EmployeeHomePage().setVisible(true);    
                }
            }
                
                else{
                    JOptionPane.showMessageDialog(null, "Fill up");
                    }
                
            }catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        /*if( jRadioButtonEmployee.isSelected()== true) {
        
            try {
                if (!jTextFieldUserName.getText().equals("")&& !jTextFieldPassword.getText().equals("")){
                   java.sql.Connection conn=null;
                   java.sql.Statement st=null;
                  //  conn = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/ssdb","root","");     
                    String sql = "SELECT * FROM emptable WHERE EmpUserName='"+jTextFieldUserName.getText()+"' AND EmpPassword='"+ jTextFieldPassword.getText()+"'";
                    ResultSet rs = st.executeQuery(sql);
                 
                if(!rs.next()){
                    JOptionPane.showMessageDialog(null, "Sorry Wrong Password.");
                    }
                
                else{
                    JOptionPane.showMessageDialog(null, "Password Matched.");
                    new EmployeeHomePage().setVisible(true);
                }
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Fill up");
                }
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
               }
       }/*
    
        /*else {
        
            try {
                if (!jTextFieldUserName.getText().equals("")&& !jTextFieldPassword.getText().equals("")){
                    //java.sql.Connection conn=null;
                    //java.sql.Statement st=null;
                    //conn = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/ssdb","root","");
                    st = conn.createStatement();     
                    String sql = "SELECT * FROM customer_registration WHERE cusername='"+jTextFieldUserName.getText()+"' AND cpassword='"+ jTextFieldPassword.getText()+"'";
                    ResultSet rs = st.executeQuery(sql);
                 
                if(!rs.next()){
                    //JOptionPane.showMessageDialog(null, "Password Matched.");
                    //new CustomerHomePage().setVisible(true);
                    JOptionPane.showMessageDialog(null, "Sorry Wrong Password.");
                    }

                else{
                    System.out.println("harami");
                    //JOptionPane.showMessageDialog(null, "Sorry Wrong Password.");
                    JOptionPane.showMessageDialog(null, "Password Matched.");
                    new CustomerHomePage().setVisible(true);
                }
                }
            
            else{
                JOptionPane.showMessageDialog(null, "Fill up");
                }
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
               }
       }*/
        
        
        
       else {
            try {
                if(!jTextFieldUserName.getText().equals("")&& !jTextFieldPassword.getText().equals("")){
                
                java.sql.Connection conn=null;
                java.sql.Statement st=null;
                conn = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/ssdb","root","");
                st = conn.createStatement();
                String sql = "SELECT * FROM customer_registration WHERE cusername='"+jTextFieldUserName.getText()+"' AND cpassword='"+ jTextFieldPassword.getText()+"'";
                ResultSet rs = st.executeQuery(sql);
                   
                if(rs.next()){
                JOptionPane.showMessageDialog(null, "Sorry Wrong Password.");
                    }
                
                else{
                    
                JOptionPane.showMessageDialog(null, "Successfull");
                new CustomerHomePage().setVisible(true);    
                }
            }
                
                else{
                    JOptionPane.showMessageDialog(null, "Fill up");
                    }
                
            }catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
   
    }//GEN-LAST:event_jButtonLogInActionPerformed
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonRegestrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegestrationActionPerformed
        this.setVisible(false);
        new RegistrationHomePage().setVisible(true);
    }//GEN-LAST:event_jButtonRegestrationActionPerformed

    private void jRadioButtonEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmployeeActionPerformed
              String radiotext="";
              if(jRadioButtonEmployee.isSelected()){
              radiotext=jRadioButtonEmployee.getText();
              }
              if(jRadioButtonCustomer.isSelected()){
              radiotext=jRadioButtonCustomer.getText();
              }
              
              
    }//GEN-LAST:event_jRadioButtonEmployeeActionPerformed
    
    private void jRadioButtonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCustomerActionPerformed
        
    }//GEN-LAST:event_jRadioButtonCustomerActionPerformed

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
       
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInHomePage().setVisible(true);
            }
        });
        try{
        conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/ssdb","root","");
        }catch(SQLException ex){
        System.out.println("SQLException" +ex.getMessage());
        System.out.println("SQLState" +ex.getSQLState());
        System.out.println("VendorError " +ex.getErrorCode());}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonLogIn;
    private javax.swing.JButton jButtonRegestration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelLogInAs;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JRadioButton jRadioButtonCustomer;
    private javax.swing.JRadioButton jRadioButtonEmployee;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}